version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nesrine-mysql
    restart: always
    environment:
      MYSQL_DATABASE: nesrine
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
